### ISSUE TITLE
ValueError: No op named GatherV2 in defined operations

### ISSUE THREAD

**Issue by gedonglai** [nikitakit/self-attentive-parser#1]
hello,I want to run ' parser = benepar.Parser("benepar_en")', but it raise  the error like this "ValueError: No op named GatherV2 in defined operations".  could you tell me your python version and tensorflow-gpu version and cudnn version. I don't know how to fix this error . thank you very much.

**Comment by nikitakit** [comment]
Thanks for pointing this out!

I'm using Tensorflow 1.8.0 (the latest version). Looks like the GatherV2 op was added in Tensorflow 1.3, so any version older than that is guaranteed not to work.

**Comment by gedonglai** [comment]
Thank you for your reply,
Could i train a chinese model by your parser?   What do I need to pay attention to?

**Comment by nikitakit** [comment]
I've never trained a Chinese model, but you're welcome to try!

You may need to modify the `load_trees` function in `src/trees.py` so that it properly reads the training data you have, but otherwise the [training instructions](https://github.com/nikitakit/self-attentive-parser#training) are in the README.

I'm going to look into releasing multilingual parsing models, but Chinese will require extra time to familiarize myself with the standard conventions and models for Chinese parsing and tokenization. The main issue is that Chinese tokenization is very different from English, and I don't know whether it's empirically better to rely on external tools or to just train the parser itself to split sequences of characters into words.

Let me know if you train any models and have any results!

**Comment by gedonglai** [comment]
Hi,
    I‘m training the chinese model, I have nothing but ctb9.0 data set. so when I run the train command it raise' AssertionError: Need at least one of : use_tags,use_words, use_chars_lstm, use_chars_concat, use_elom". which one i should select?

**Comment by nikitakit** [comment]
`--use-words` enables learned word embeddings, which is probably the best thing to start with.

`--use-chars-lstm` enables using a character LSTM. This will result in a better parser, but may require more hyperparameter tuning. For English this option is best used in combination with `--d-char-emb 64`, but you'll probably want to use a value higher than 64 because there are many more Chinese characters than letters in the English alphabet.

To use both word embeddings and a character LSTM at the same time, you can pass both options: `--use-words --use-chars-lstm`.

I wouldn't recommend using `--use-chars-concat`, and `--use-tags`/`--use-elmo` won't work without additional pre-trained models.

**Comment by nikitakit** [comment]
What happens if you disable`strip_top` when loading the trees? This [is already done](https://github.com/nikitakit/self-attentive-parser/blob/master/src/trees.py#L146) for some languages.

The code is not set up to deal with empty parse trees: there needs to be at least one label above the part-of-speech tag level. The English treebank annotates single-word fragments as FRAG, but for treebanks that don't do this the simplest fix is to keep the root node.

**Comment by gedonglai** [comment]
Thankyou very much.
         You are so friendly to me.  heartfelt thanks.

**Comment by gedonglai** [comment]
Hi,
     I have a new question. how many epochs do i need to train.  thank you

**Comment by nikitakit** [comment]
I updated the README to include a tensorflow version dependency, so the original issue should now be addressed. I'm closing this, but feel free to comment or open another if you have any more questions/bugs.
