### ISSUE TITLE
Pre-trained model Performance inconsistent with the one in README

### ISSUE THREAD

**Issue by GaryYufei** [nikitakit/self-attentive-parser#4]
Hi, 

thanks for this great work. I installed the parser ("benepar_en") using pip and tested its performance the WSJ 23 section. What I found is that, the performance is higher than the number claimed in README (in my side, it shows 95.98 (vs 95.07 in README)). I am wondering if the pre-trained model in pip has used WSJ 23  in training? It seems unclear what is used to train the pip model.

Thanks in advance.

**Comment by nikitakit** [comment]
The "benepar_en" model is just a compressed version of the model we report in our paper. Sorry if that was unclear. We follow the standard splits: 2-21 for training, 22 for dev, and 23 for test. If you'd like to check any of the details, the code is all in the repo and the command to train the model is in the README (search for `--use-elmo`).

What evaluation are you using that's getting almost 96 F1? I really wish the parser was that accurate, but that isn't the number I've gotten in any of my evaluations. The 95.07 number was produced by evalb (see the `EVALB` directory in the repo) using the `COLLINS.prm` parameter file, and includes sentences of all lengths (not just up to length 40). I know that when I was getting started with parsing it took me a while to track down what the standard evaluation procedure is, especially since most parsing papers aren't very detailed on this point. Is it possible that you're running the evaluation differently?

**Comment by GaryYufei** [comment]
Hi,

OK. I finally found my mistake which happened in constructing the golden parsing tree from WSJ corpus. Thanks for your help!! I will close the issue.
