### ISSUE TITLE
Mark as unmaintained?

### ISSUE THREAD

**Issue by swetepete** [nikitakit/self-attentive-parser#94]
This library appears very useful but it appears there hasn't been activity on it since around May 2021.

I had a couple installation issues which seemed to stem from the library not being up to date with newer versions of its dependencies, such as protobuf.

I think it could be good if people could see that this library is no longer maintained.

**Comment by nikitakit** [comment]
I don't think it's quite accurate to say that the library is unmaintained. I pay close attention to any github issues that would signal a regression compared to past behavior, and there haven't been any such reports to the tracker. If you see something going on with dependencies, please file an issue with steps for how to reproduce the problem.

A better description of the situation is that the job of this package is to implement exactly the parsing method described in my paper, and no further changes are required for that (until something breaks). I take inspiration from the [evalb software](https://nlp.cs.nyu.edu/evalb/), which basically hasn't changed since 2006 and still does its job just as well today as it did then -- no changes required. It would be wonderful if I could get even a fraction of that shelf life. And if something changes out from under it in terms of dependencies, I'll fix it.

**Comment by swetepete** [comment]
Sorry, my mistake. Thanks for the clarification. Sounds like a great idea. Thank you.
